	<meta name="viewport" content="width=device-width, initial-scale=1" />
		<meta charset="utf-8" />
		<title>Companion Care</title>
		<link href="../../CSS-Main.css" rel="stylesheet" type="text/css" />

		<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

		<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
		<script type="application/ld+json">
			{
				"@context": "http://schema.org",
				"@type": "LocalBusiness",
				"name": "Centry Care Plus LLC",
				"telephone": "443-599-8280"
			}
		</script>
		<script type="module" src="../../plugins/scroll-to-highlight.js"></script>