<?php require_once 'plugins/hil/functions.php'; ?>
<!DOCTYPE html>
<html>

<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1" />
		<meta charset="utf-8" />
		<title>Companion Care</title>
		<link href="CSS-Main.css" rel="stylesheet" type="text/css" />

		<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

		<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
		<script type="application/ld+json">
			{
				"@context": "http://schema.org",
				"@type": "LocalBusiness",
				"name": "Centry Care Plus LLC",
				"telephone": "443-599-8280"
			}
		</script>
		<script type="module" src="./plugins/scroll-to-highlight.js"></script>
</head>

<body>
  <header>
        <div class="Row">
        <div class="Header-Left">
            <a href="Contact.html">
             Let us know what's on your mind.<br>
            <i class="fa-light fa-envelope"></i> Send a Message
                </a>
            </div>
    <div class="Logo">
        <a href="index.html">
            <img src="Images-Main/Logo.png" alt="Logo">
            </a>
        </div>
        <div class="Header-Right">
            <div class="Line-1">
                We're here to help.
                </div>
            Click to Call:  <a href="tel:443-599-8280"><i class="fa-solid fa-mobile-screen-button"><!--Icon--></i> 443-599-8280
            </a>
            </div>
            </div>
        <div class="Row">
        <hr>
            </div>
    </header>
	<div class="Nav-Row">
		<div class="Nav-Inline-Block">
			<nav id="main-nav" aria-label="Main Navigation">
				<button id="menu-toggle" class="menu-toggle" aria-controls="main-menu" aria-expanded="false">
                    <i class="fa-solid fa-bars open"><!--Icon--></i>
					<i class="fa-solid fa-xmark close"><!--Icon--></i>
                   <span>Menu</span>
				</button>
				<menu id="main-menu">
					<li><a href="index.html">Home</a></li>
					<li><a href="Services.html">Services</a></li>
					<li><a href="About.html">About Us</a></li>
                    <li><a href="/Blog">Our Blog</a></li>
                    <li><a href="Resources.php">Knowledge Center</a></li>
					<li><a href="Careers.html">Careers</a></li>
					<li><a href="Contact.html">Contact Us</a></li>
				</menu>
			</nav>
		</div>
	</div>
    <main>
        <div class="Row-Pattern-Dark">
            <div class="Row-Pattern-BG">
        <div class="Box-80">
            <h1>Knowledge Center</h1>
            <div class"Text">
        As a service from us to you: we have gathered thousands of health information articles. All the articles are authoritatively sourced, constantly updated, bi-lingual, and searchable. Please come back any time you want straightforward, correct answers to health information questions.
            </div>
            </div>
        </div>
            </div>
	<?= template_part('container', [
		'links' => [
			'Alzheimers Caregivers',
			'Dementia',
            'Diabetes',
            'Falls',
            'Flu',
            'Heart Disease Prevention',
            'Seniors'
		]
	]); ?>
        </main>
<div class="Row-Contact">
			Let us know what's on your mind. We will help.<br />
    Click to Call: <a href="tel:443-599-8280">443-599-8280</a>
    <h2>Request a no-obligation, in-home consultation.</h2>
			<br />

			<form
				class="form"
				method="POST"
				action="sendmail.php"
				enctype="multipart/form-data"
			>
				<div class="form-row">
					<div class="input-field required">
						<label class="field-label" for="name">
							<i class="fa-duotone fa-id-card"><!--Icon--></i>
							Name:
						</label>

						<input
							class="field-input"
							type="text"
							name="name"
							required
						/>
					</div>

					<div class="input-field">
						<label class="field-label" for="email">
							<i class="fa-duotone fa-at"><!--Icon--></i>
							Email:
						</label>

						<input
							class="field-input"
							name="email"
							type="email"
							pattern="(?!(^[.-].*|[^@]*[.-]@|.*\.{2,}.*)|^.{254}.)([a-zA-Z0-9!#$%&amp;'*+\/=?^_`{|}~.-]+@)(?!-.*|.*-\.)([a-zA-Z0-9-]{1,63}\.)+[a-zA-Z]{2,15}"
							title="Valid email addresses must have text@text.TLD"
						/>
					</div>

					<div class="input-field">
						<label class="field-label" for="phone">
							<i class="fa-duotone fa-mobile"><!--Icon--></i>
							Phone:
						</label>

						<input
							class="field-input"
							name="phone"
							type="text"
							data-imask="000-000-0000"
						/>
					</div>
				</div>

				<div class="input-field required">
					<label class="field-label" for="message">
						<i class="fa-duotone fa-message-lines"><!--Icon--></i>
						Message:
					</label>

					<textarea
						class="field-input"
						name="message"
					></textarea>
				</div>

				<div class="captcha-field">
					<div class="captcha">
						<img class="captcha-image" src="captcha.php" alt="CAPTCHA" />

						<button
							type="button"
							class="button captcha-refresh-btn"
							title="Reset Captcha Image"
						>
							<i class="fa-solid fa-arrows-rotate"><!--Icon--></i>
						</button>
					</div>

					<div class="input-field required">
						<label for="captcha-response" class="field-label">
							<strong>SPAM CHECK:</strong>
							Enter the characters you see in the image
						</label>

						<input
							type="text"
							name="captcha-response"
							class="field-input"
							required
							placeholder=""
						/>
					</div>
				</div>

				<button type="submit" class="button">
					Send
					<i class="fa-solid fa-paper-plane"><!--Icon--></i>
				</button>
			</form>
		</div>  <div class="Admin">
        <a href="/Blog/admin" target="_blank">EZPost</a>
        <a href="https://login.securepanel.us" target="_blank" rel="nofollow">SecurePanel</a>
        <a href="https://login.secureemail.us" target="_blank" rel="nofollow">SecureEmail</a>
        <a href="/Employee/" target="_blank" rel="nofollow">Employee</a>
        </div>
    <div class="BackToTop">
			<img id="CloseBTT" src="Images-Main/close.png" alt="close" />
			<a href="tel:443-599-8280">Call Now<br />443-599-8280</a>
			<a href="Contact.html">
				Send a Message<br /><i class="fas fa-envelope"><!--Icon--></i>
			</a>
			<a id="BackToTop"><i class="fas fa-arrow-circle-up"><!--Icon--></i></a>
		</div>
    
	<script src="./plugins/jquery.1.11.1.min.js"></script>
		<script src="./plugins/jquery.mobile.custom.min.js"></script>
		<script src="./plugins/back-to-top.js"></script>
		<script type="module" src="./plugins/main.js"></script>
</body>

</html>
